### ISSUE TITLE
Healthcheck fails in uaa-release 68 if uaa.port is not set

### ISSUE THREAD

**Issue by richardTowers** [cloudfoundry/uaa-release#101]
We (GOV.UK PaaS) are in the process of upgrading from cloudfoundry/uaa-release v66 to v68 for our bosh director.

After the upgrade UAA started failing it's monit healthcheck. From monit.log:

```
[UTC Feb  7 16:12:38] error    : HTTP error: Server returned status 400
[UTC Feb  7 16:12:38] error    : 'uaa' failed protocol test [HTTP] at INET[localhost:8443/healthz] via TCP
```

Making the healthcheck manually indicates that this is an issue with using an HTTP healtcheck for an HTTPS endpoint:

With HTTP:

```
bosh/0:~# curl -vk http://localhost:8443/healthz
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 400
< Content-Type: text/plain;charset=ISO-8859-1
< Connection: close
<
Bad Request
This combination of host and port requires TLS.
```

With HTTPS:

```
bosh/0:~# curl -vk https://localhost:8443/healthz
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: 10.0.0.6 (does not match 'localhost')
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=USA,O=Cloud Foundry,CN=10.0.0.6
*        start date: Wed, 09 Jan 2019 11:58:45 GMT
*        expire date: Thu, 09 Jan 2020 11:58:45 GMT
*        issuer: CN=bosh-CA
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /healthz HTTP/1.1
> Host: localhost:8443
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200
< Content-Type: text/plain;charset=ISO-8859-1
< Content-Length: 3
< Date: Thu, 07 Feb 2019 16:41:31 GMT
<
ok
* Connection #0 to host localhost left intact
``` 

The [monit config](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/monit#L27) for this release always uses an HTTP healthcheck, whether it's using the HTTP port or the HTTPS port.

You may well wonder why this fails in uaa-release v68, but didn't fail in uaa-release v66. I think this is due to a combination of bugs in Monit and Tomcat 8 (which has been upgraded to Tomcat 9 in v68).

In Tomcat 8, the HTTPS connector will respond with garbage bytes if you send it a plain HTTP request. In Tomcat 9 it will work out that this is not an HTTPS request, and respond with a plain HTTP 400.

Monit's HTTP healthcheck treats badly-formed HTTP responses as successful (!?), but treats HTTP 400s as failures.

The combination of Tomcat 8's garbage responses and Monit's broken HTTP healthcheck meant that this bug only surfaced following the Tomcat upgrade.

For now it's possible to work around this issue by setting `uaa.port`, which causes uaa to listen on an HTTP port and monit to healthcheck that. A better fix would be for monit to use an HTTPS healthcheck if UAA is only listening on HTTPS.

**Comment by thomasmitchell** [comment]
I believe the version of monit stapled to BOSH is too old to know how to HTTPS health check. To fix this, we can lean on the needing an HTTP server up, but have a configurable way to only have it listen on loopback.

Alternatively, the healthcheck could be changed to a script that actually performs an HTTPS healthcheck using curl/`<your https utility here>`

**Comment by cfryanr** [comment]
Hi, thanks for reporting this issue.  We reproduced this issue and confirmed your analysis.  However, we're in need of a creative solution.  @thomasmitchell is right that the old version of monit used by BOSH does not support https health checks.  @thomasmitchell, could you shed some more light on your suggestion to use curl or another arbitrary command?  That would be perfect, but I don't see a way to implement that in the monit docs.

**Comment by thomasmitchell** [comment]
So, I had only gotten the impression that was possible from a quick skim. I wonder if its possible to abuse the program check functionality to achieve the desired effect? I'm sorry that I can't be more directly helpful in that regard - I've never tried such a thing myself.

**Comment by daviddob** [comment]
After digging into `monit v5.2.5` for far too long I do not believe it is possible to check an HTTPS endpoint with the stemcell compiled version. To check an HTTPS endpoint, monit v5.2.5 needs to be compiled with special flags to enable SSL checks and on the stemcells it does not appear to be enabled. If it were enabled, the health check would look like the following:

```
if failed
  port 443
  type TCPSSL tlsv1 ( Can be any of the following <AUTO | SSLV2 | SSLV3 | TLSV1 | TLSV11 | TLSV12 | TLSV13>)
  protocol http
  request "/healthz"
  with timeout 60 seconds for 64 cycles
then restart
```
As a stemcell level change to monit is likely out of the question, and I also have not found a way to make an http(s) request via another method using monit, another approach may be required.

----

It would be possible to change the configuration such that monit always attempts to health check on http using the `uaa.port` and if a user disables the `http` endpoint, instead of disabling the connector entirely, set it to listen on loopback only using a default port.

The necessary changes would be to add the `address="127.0.0.1"` parameter to this [connector](https://github.com/cloudfoundry/uaa-release/blob/477360ff379ebdf4b42c262593880c595a209f68/jobs/uaa/templates/config/tomcat/tomcat.server.xml.erb#L50) in the event of a "disabled" http port and change the logic to leave the connector enabled. It would also require a minor tweak to the [monit](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/monit#L4) file to always check using the http `uaa.port` (or default if "disabled")

This could similarly be accomplished by exposing new parameters for `uaa.listen_address` and `uaa.ssl.listen_address` and disallowing the `-1` value for `uaa.port`.

----

Alternatively, in place of the `http` check a `tcp` check can be made with monit via
```
if failed
  port <port>
  type TCP
  with timeout 60 seconds for 64 cycles
then restart
```
however you would lose some of the resiliency of the health check as it would only be checking that a server was running on that port (not necessarily a status code response).

**Comment by thomasmitchell** [comment]
I believe that with the addition of `uaa.localhost_http_port`, this has effectively been addressed.
