### ISSUE TITLE
How to locate uaa.log file inside docker

### ISSUE THREAD

**Issue by akshaygik** [cloudfoundry/uaa-release#223]
Hi, I am using **docker version cfidentity/uaa:74.23.0**
As per documentation I should see **uaa.log** file generated in /cargo/conf/logs/
But I am not able to locate such directory inside my container. 
This is what at most I can see from my root directory but it doesn't contain uaa.log file:

> app  bin  boot  cnb  dev  etc  home  layers  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  workspace
$ cd var
$ ls
backups  cache  lib  local  lock  log  mail  opt  run  spool  tmp
$ cd log
$ ls
alternatives.log  apt  bootstrap.log  btmp  dpkg.log  faillog  fontconfig.log  journal  lastlog  sysstat  tallylog  wtmp

Do I need to to configure anything in my uaa.yml in order to generate this log file?

**Comment by shamus** [comment]
Oh hi. This repository is used to manage the BOSH release of the UAA. It does not pertain to the containerized release of the UAA. The [UAA repo](https://github.com/cloudfoundry/uaa) is a better place for discussions about the image.

Anyway, the UAA image isn't well documented yet, it's still being developed. The application delivers log output to stdout. Meaning: there is no `uaa.log` when using the image.

This is a change from the BOSH release. Logging to standard out is pretty standard in the container world. This approach gives greater flexibility for log management, because another system can decide on a log management implementation (i.e. stdout can be directed to a file, a log management service, or some other solution).

**Comment by akshaygik** [comment]
great, Thanks for reply @shamus
