### ISSUE TITLE
Move uaa database migration to pre-start script

### ISSUE THREAD

**Issue by andreas-kupries** [cloudfoundry/uaa-release#91]
# Proposal

Move the execution of the database migrations for UAA out of the main
job of the release (`uaa`) into a pre-start script.

# Reasoning

We have seen database migrations taking a very long time, in different
environments within our private cloud across assorted types of
hardware and clusters, to the point that monit considers the UAA
process dead (*) and restarts it mid-migration. This reads as a race
condition.

In testing the problem can be induced by slowing down the
disks/volumes accessible to the mysql node via the `stress` utility
with the `--io` and `--hdd` options.

(*) The timeout rule is triggered:

```
    if failed port <%= p("uaa.port") %> protocol http
      request "/healthz"
      with timeout 60 seconds for 15 cycles
    then restart
```

It appears that during the database migrations UAA is not responding
to the `/healthz` endpoint. That makes sense. While the migrations are
on-going UAA cannot serve requests, thus is by definition not healthy
yet.

# Alternate solutions

A possible alternate solution is to extend the timeout, for example 10
times to 600.

This however introduces the problem that when the UAA truly gets
stuck/hung the proper restart is now delayed by the same factor of 10.

# A wrong solution

Having UAA respond to `/healthz` during migration. 

To reiterate, while the migrations are on-going UAA cannot serve
requests, thus is by definition not healthy yet.

Responding to `/healthz` will make a fake claim causing other
components to send requests too early, and further, truly stuck
migrations will not be killed anymore ever, too.

# Conclusion

Overall the best solution seems to be to run the migrations from a
pre-start script.

**Comment by DennisDenuto** [comment]
Hi @andreas-kupries 
Thanks for creating this issue. This is an interesting problem you have outlined.

FYI We have increased the number of cycles attempted to start the UAA to 64 (This was an attempt at solving a different problem where tomcat would startup slowly if not enough entropy was generated when reading from /dev/random assuming it wasn't configured to read from /dev/urandom)

Also from our testing, there is a constraint imposed by `monit` of 64 being the maximum number of cycles. (This rules out the alternate solution of bumping to 600).

I have a concern about putting the db migration logic in the `pre-start`. As an example: If the `uaa_postgres` job is co-located with the `uaa` on the same vm, the `uaa_postgres` job will only startup during the `start` lifecycle. However the `uaa` migration job would require that this db job also start during the pre-start lifecycle so that it can perform its database migration. 

It also appears that the [mysql bosh release](https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/mysql/monit) also has the job starting during the `start` lifecycle.

I think this is a [known issue / limitation](https://github.com/cloudfoundry/bosh/issues/1151)

I'll leave this open for discoverability since it's currently a technical limitation of UAA release.

**Comment by DennisDenuto** [comment]
Hi @andreas-kupries 

Another approach would be we improve the `healthz` endpoint to indicate whether it can receive HTTP requests.

It would work like the following:
1. The `uaa` db migration occurs during the `start` phase.
1.1. While the db migration is taking place, the `uaa` `/healthz` endpoint indicates that it is `healthy` *and* that it is unable to serve http requests.
1.2. When the db migration has finished, and the uaa has fully started up, the `uaa` `/healthz` endpoint indicates that it is `healthy` *and* that it is able to serve http requests.
2. Monit determines the healthiness of the `uaa` by calling the `/healthz` endpoint.
2.1. If `/healthz` returns a `200` then the `uaa` job is seen as healthy/running
3. `route_registrar` checks the `/healthz` endpoint
3.1. If the db migration is still running, then `/healthz` returns `200` *and* indicates that it is unable to serve http requests.
3.1.1. In this case, `route_registrar` does not register a route to this 'unhealthy' uaa instance
3.2. If the db migration has finished, then `healthz` returns `200` *and* indicates that it *is* able to serve http requests.
3.2.1. In this case, `route_registrar` *does* register a route to this 'healthy' uaa instance

cc @jhamon @tnwang

**Comment by viovanov** [comment]
@DennisDenuto maybe we could follow the capi-release approach?
https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec#L255-L257

**Comment by DennisDenuto** [comment]
Hi @viovanov I think that is an option worth considering. It does come with a couple of tradeoffs worth outlining:
1. It doesn't solve the issue if you want to co-locate your db with UAA. (Maybe this is ok? since i am doubtful that this specific deployment setup is common)
1. It requires yet another operator config (`run_prestart_migrations`), thus slightly increasing operator complexity. I think to be backwards compatible / simplify the deployment manifest we could set the default value to `true`. (This default value will probably work for most deployments, except for the ones that co-locate the db job and uaa. see 2.1)
    1. Relying on a default value of `true` means that in the event a database job is co-located with the uaa on the same instance group, the deployment will fail. I think work would need to be done to improve the error message to the operator if a migration fails due to being unable to connect to the database. specifically the error message should make mention of `run_prestart_migrations` so that operators can discover that this property *might* be the issue. 

I think some additional changes to how UAA migrates data would be valuable:
1. Allow a way to *just* run db migrations without having to deploy + run the uaa as a web app. (Currently db migrations run during the web app initialization phase). This will greatly simplify the `pre-start` script because the failure signal for db migrations and any other problems that might occur during uaa starting up are hard to tell apart. i.e. Did the UAA fail to start up because the db migration failed, or did it fail to start up because it is missing some required property (yet managed to successfully migrate the db)? hard to tell from the `/healthz` endpoint since it returns a `503` for all error cases.
1. From now on, make new db migrations idempotent. Currently if a migration fails halfway due to some flakiness (or because it took too long), UAA is left in a state where manual intervention is required. (This won't help operators if the db migration fails halfway for an 'old' migration that isn't idempotent.)

**Comment by hsinn0** [comment]
Closing old issue for no activities
